// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwIrHwUJ9Di_tjUiDXte6q0yTrSdQFB0A',
    appId: '1:624412580196:web:eae8ec906abd192ceb8271',
    messagingSenderId: '624412580196',
    projectId: 'tewos-technology',
    authDomain: 'tewos-technology.firebaseapp.com',
    storageBucket: 'tewos-technology.appspot.com',
    measurementId: 'G-MG31RRR6H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkv3ShAQcM6SxBAj1q_oe5M-sx4ilFinA',
    appId: '1:624412580196:android:68aa515518b5e101eb8271',
    messagingSenderId: '624412580196',
    projectId: 'tewos-technology',
    storageBucket: 'tewos-technology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxT2BFbkbMlRtwcIc31y1whOLg8SxmXwk',
    appId: '1:624412580196:ios:2ca77a02b4513cbdeb8271',
    messagingSenderId: '624412580196',
    projectId: 'tewos-technology',
    storageBucket: 'tewos-technology.appspot.com',
    iosBundleId: 'com.example.payGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxT2BFbkbMlRtwcIc31y1whOLg8SxmXwk',
    appId: '1:624412580196:ios:2ca77a02b4513cbdeb8271',
    messagingSenderId: '624412580196',
    projectId: 'tewos-technology',
    storageBucket: 'tewos-technology.appspot.com',
    iosBundleId: 'com.example.payGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwIrHwUJ9Di_tjUiDXte6q0yTrSdQFB0A',
    appId: '1:624412580196:web:77d582245da85ec8eb8271',
    messagingSenderId: '624412580196',
    projectId: 'tewos-technology',
    authDomain: 'tewos-technology.firebaseapp.com',
    storageBucket: 'tewos-technology.appspot.com',
    measurementId: 'G-M6STFMR4DX',
  );
}
